In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
v1 = np.array([10,6,20])
v2 = np.array([5,10,14])
print(v1)
print(v2)

[10  6 20]
[ 5 10 14]


In [6]:
print(v1 + v2)

[15 16 34]


In [7]:
print(v1 - v2)

[ 5 -4  6]


In [8]:
print(v1 *5)

[ 50  30 100]


In [9]:
print(v1.dot(v2))

390


In [11]:
m1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(m1)
print("==========================")
m2 = np.array([[1,2,0],
                [4,10,6],
                [7,8,9]])
print(m2)
print("===========================")
print(m1.dot(m2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  0]
 [ 4 10  6]
 [ 7  8  9]]
[[ 30  46  39]
 [ 66 106  84]
 [102 166 129]]


In [13]:
s = np.array(5)
print(s.ndim) # @property act as attribute call without ()
print(s.shape)

0
()


In [17]:
v1 = np.array([1,2,3])
print(v1.ndim) # @property act as attribute call without ()
print(v1.shape)

1
(3,)


In [15]:
m1 = np.array([[1,2,3],
               [2,7,5],
               [9,8,7]])
print(m1.ndim) # @property act as attribute call without ()
print(m1.shape)

2
(3, 3)


In [19]:
vec1 = np.array([1,2,3,4,5,6])
mat_1 = vec1.reshape(3,2)
print(mat_1)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
def reshape_col_vec(mat):
    mat = vec1.reshape(mat.shape[0],1)
    return mat

In [24]:
vec2 = np.array([1,2,3,4])
mat_2 = vec2.reshape(vec2.shape[0],1)
print(mat_2)

[[1]
 [2]
 [3]
 [4]]


In [25]:
vec2 = np.array([1,2,3,4])
vec2.shape

(4,)

In [28]:
vec2 = np.array([1,2,3,4])
mat_2 = vec2[:,None]
print(mat_2)

[[1]
 [2]
 [3]
 [4]]


In [34]:
# object -> string -> float -> int -> bool
mat_3 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9.2]])
print(mat_3.dtype)
print(mat_3)

float64
[[1.  2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9.2]]


In [35]:
# object -> string -> float -> int -> bool
mat_4 = np.array([[True,False,True],
                  [4,True,True]])
print(mat_4.dtype)
print(mat_4)

int64
[[1 0 1]
 [4 1 1]]


In [38]:
# object -> string -> float -> int -> bool
mat_5= np.array([[1.1,"2",3],
                  [4,5,6.2],
                  [7,8,9.2]])
print(mat_5.dtype)
print(mat_5)

<U32
[['1.1' '2' '3']
 ['4' '5' '6.2']
 ['7' '8' '9.2']]


In [40]:
class C:
    x = 3
    
o1 = C()

In [52]:
# object -> string -> float -> int -> bool
mat_6 = np.array([[1,2,3],
                  [4,5,6],
                  [2,8,9.2]])
print(mat_6.dtype)
print(mat_6)




float64
[[1.  2.  3. ]
 [4.  5.  6. ]
 [2.  8.  9.2]]


In [53]:
mat_6.astype(float)
mat_6

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [2. , 8. , 9.2]])

In [54]:
f_mat = mat_6.astype(float)
f_mat

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [2. , 8. , 9.2]])

In [58]:
v1 = np.array([1,2,3,4,5])
v1[-2]

np.int64(4)

In [59]:
f_mat[1,-2]

np.float64(5.0)

In [60]:
v1[-3:-1]

array([3, 4])

In [64]:
mat_7 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [0,0,0]])

mat_7[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [65]:
mat_7[-3:-1,-3:-1]

array([[4, 5],
       [7, 8]])

In [66]:
mat_7.T

array([[1, 4, 7, 0],
       [2, 5, 8, 0],
       [3, 6, 9, 0]])

In [69]:
mat = np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
mat = np.ones((3,4))
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [71]:
mat = np.full((3,3),4)
mat

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [72]:
mat = np.empty((3,3))
mat

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [2. , 8. , 9.2]])

In [74]:
angels = np.arange(0,361,90)
angels

array([  0,  90, 180, 270, 360])

In [ ]:
def image_rotate(angle):
    return angle 

In [75]:
vec = np.linspace(0,10,num=10)
vec

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])